### PR TITLE
Update to WT 5.1.6

### PR DESCRIPTION
**Pull request by lucagasparini**
update release wt-5.1.6

### CODE REVIEW

**Comment by lucagasparini** [comment]
The autobuild procedure has failed.
Any ideas on the reason for the failure?
@gbulfon see the details of travis.

**Comment by gbulfon** [comment]
Can you run again the automated build?
We're checking on a clean NS7, cloned the build gate and started a scratch build, we had some strange errors once, but then not a second time.
Looks like maven servers did not respond correctly?

**Comment by gbulfon** [comment]
We just successfully finished a clean build and deploy of the new version on a clean NS7.
Probably some temporary problem on maven repos.
Please retry build.

**Comment by Amygos** [comment]
NethServer/dev#5423

**Pull request merged**
