### PR TITLE
Update to WT 5.1.5

### PR DESCRIPTION
**Pull request by gsanchietti**
Upgrade to new upstream release 5.1.5

NethServer/dev#5414

### CODE REVIEW

**Comment by lucagasparini** [comment]
The installation of the package breaks the application.

The log shows errors related to the lack of some jars.
It seems that the build does not explode the war as it was built, it extracts only prefixed things:

From the Travis log: https://travis-ci.org/NethServer/webtop5/builds/330263601
 
unzip /srv/makerpms/rpmbuild/SOURCES/webtop-webapp-5.war 'WEB-INF / * sonicle * .jar' 'WEB-INF / * webtop * .jar' META-INF / MANIFEST.MF META-INF / context.xml META-INF / data-sources.xml WEB-INF / classes / logback.xml WEB-INF / shiro.ini WEB-INF / web.xml -d root / var / lib / tomcats / webtop / webapps / webtop

Virtually the "* sonicle *" and "* webtop *" jars plus the various configuration files.
All other jars are not found in the build.

The WAR should be exploded as it is, it is ready to use as specified by j2ee.
It is the development team that decides which jar it should contain during the maven build.

**Comment by gsanchietti** [comment]
Actually, the package is split into 3 sub-packages:
- webtop5-core
- webtop5-libs
- webtop5-zpush

This choice has been taken by the community to lower the impact of WebTop updates on mirrors and limit the used bandwidth during the updates.
Currently, WebTop5 packages uses around the 14% of disk space of the whole NethServer updates repository.

The implementation is working since months and can be adapted to upstream needs, if only upstream documents the modifications between various releases.

By the way, I can fulfill upstream needs by reverting the current implementation and move back to a single package which contains everything. Please, take in mind that every update will be around 100MB in size.

**Comment by gsanchietti** [comment]
The new package is named `webtop5` and replaces both `webtop5-core` and `webtop5-libs`.
As requested by upstream WebTop project, it should contain all files exploded from the jar.

```
2018-01-19 14:01:46 [ERROR] c.sonicle.webtop.core.servlet.Login - Error
java.lang.NullPointerException: null
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1326)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
        at com.sonicle.webtop.core.app.WebTopApp.lookupResource(WebTopApp.java:1019)
        at com.sonicle.webtop.core.app.WebTopApp.lookupResource(WebTopApp.java:994)
        at com.sonicle.webtop.core.servlet.Login.writePage(Login.java:127)
        at com.sonicle.webtop.core.servlet.Login.processRequest(Login.java:110)
        at com.sonicle.webtop.core.app.AbstractServlet.doGet(AbstractServlet.java:71)
```
The application can't find some resources which needs to be loaded, reference: https://github.com/sonicle-webtop/webtop-core/blob/master/src/main/java/com/sonicle/webtop/core/app/WebTopApp.java#L1018

@lucagasparini @malbinola @gbulfon any hint on this?

**Comment by gbulfon** [comment]
Where can we see the complete content of webapps/webtop ?
Be sure first that it contains ALL of and JUST the content of the war.
For example, we removed the META-INF/context.xml, and it must not be there.
If there is an installed machine we can check, it would be easier to help.

**Comment by lucagasparini** [comment]
@gbulfon
You can use the usual machine (wt5dev).
I've just installed the new package.

**Comment by gsanchietti** [comment]
Just download the linked RPM and inspect it with an archive manager application.
If you're on a CentOS/Fedora, you can use:
```
wget http://packages.nethserver.org/nethserver/7.4.1708/autobuild/x86_64/Packages/webtop5-1.1.6-1.7.pr6.g8b9f215.ns7.noarch.rpm
rpm -qlp webtop5-1.1.6-1.7.pr6.g8b9f215.ns7.noarch.rpm > rpm_content
```

If you'd like to see a running machine, you can install your own using free dply.co service: https://community.nethserver.org/t/configure-nethserver-7-dc-vpns-on-a-dply-co-vps/7369

Just as quick help, here is the pastebin of the rpm content: https://pastebin.com/4t4ykZ6T

**Comment by gbulfon** [comment]
There is a a bit of mess in the webapp content, not reflecting the original war deployment.
Everything must be left as is from the war, in this case I found WEB-INF/shiro.ini different from the war.
Also, we no more deploy META-INF/context.xml, it must not be there.
Then, the only files that you should change are META-INF/data-sources.xml and WEB-INF/classes/logback.xml to reflect your db passwords and loggin scheme - instead they're left as original.

So, I suggest:
- during deploy completely remove the webapps/webtop
- unpack the new war inside a clean webapps/webtop
- update META-INF/data-sources.xml and WEB-INF/classes/logback.xml with your custom ones

Meanwhile, to let me test the dev machine, can you provide me the modified data-sources.xml and logback.xml so I can test if it would work?

**Comment by gbulfon** [comment]
sorry, I found it by myself, the dev machine works with these changes:
- removed META-INF/context.xml
- put WEB-INF/shiro.ini and WEB-INF/web.xml as from built war
- changed WEB-INF/classes/logback.xml to point the correct log
- changed META-INF/data-sources.xml with correct postgres credentials (sonicle and pass from secrets)

**Comment by gsanchietti** [comment]
Both `content.xml` and `shiro.ini` are straight from the war generated by sonicle-werbtop5-gate:
```
$ unzip -l webtop-webapp-5.war  | grep -e "META-INF/context.xml" -e "shiro.ini"
     1499  01-19-2018 12:46   WEB-INF/shiro.ini
       99  01-19-2018 12:46   META-INF/context.xml
```
The war is simply exploded: https://github.com/gsanchietti/webtop5/blob/wt-5.1.5/webtop5.spec#L34

Do you think its better to ship the entire war without unzipping it?

> during deploy completely remove the webapps/webtop

The rpm tool already does it before applying the new configuration.

> unpack the new war inside a clean webapps/webtop

Already done

>update META-INF/data-sources.xml and WEB-INF/classes/logback.xml with your custom ones

Already done by `nethserver-webtop5-update` event

> Meanwhile, to let me test the dev machine, can you provide me the modified data-sources.xml and logback.xml so I can test if it would work?

No, since each installation generate its own password, but I can link what is generated on my test machine:
- https://pastebin.com/ynYvN4Wa
- https://pastebin.com/bmuE3FRx

**Comment by gbulfon** [comment]
Ok, I see the context.xml can be left there, it doesn't affects your installation.
It works also when it's there.
But on the dev machine I found an old shiro.ini, I had to update it.

**Comment by gbulfon** [comment]
do you have a link to download the war from the final build?

**Comment by gsanchietti** [comment]
> do you have a link to download the war from the final build?

Of course, just unpack the source RPM, you will find a `webtop-webapp-5.war` inside:
http://packages.nethserver.org/nethserver/7.4.1708/autobuild/Source/SPackages/webtop5-1.1.6-1.7.pr6.g8b9f215.ns7.src.rpm

If need, I can hack and change any file during the rpm build.

**Comment by gbulfon** [comment]
Ok, we've found the problem, this component was not pushed:

https://github.com/sonicle-webtop/webtop-webapp

so, it was not containing latest changes (deleted context.xml and new shiro.ini)

We updated the 5.1.5 tag with the new pushed component.
This time you should get all the correct files.
In any case, after unpack, you should update the two files with your customizations:
META-INF/data-sources.xml and WEB-INF/classes/logback.xml

Try again this. Meanwhile we're going to push new changes to have spanish translations included.

**Comment by gbulfon** [comment]
BTW, we're having an issue pulling the transifex files, which are pulled with a wrong encoding format.
We expect unicode characters to be encoded as ascii \u01234 , while we get the encoded char inside.
I see this is a common problem, but we cannot seem to fix it.
Do you have any idea?
We cannot push spanish translations with these wrong files, we will need to open each (and they are many) and convert them using an online tool: this cannot be done for every translation.

**Comment by gsanchietti** [comment]
I've generated a new build after modification to webtop-webapp repository and now the web applications starts correctly.

About Transifex language files, I think you should handle the UTF8 format itself. If Java can't handle such format, you probably need to convert it to ASCII during the build process. But @DavidePrincipi can probably give you some advises since he knows the platform better than me.

**Comment by gbulfon** [comment]
Great. Once we're all set, I will check for a possible "dircmp" or "diff something" to keep track of changing jar files, should be easy via shell once I have previous and new war.

The java properties are easily managed via ascii unicode escaping, so thay can be easily edited anywhere, that's how automatically NetBeans manage those files (allowing to write and read àèìòù but automatically mantaining the file as ascii escaped codes).
Reading around, Transifex does not directly manage this situation, we're looking some ways to automatically convert them as needed.

**Comment by malbinola** [comment]
Here we are, we have updated the 5.1.5 tag including spanish and german translations.

**Comment by gsanchietti** [comment]
I just needed to take a couple of screenshot of the admin access, but after admin login the page is blank.
I tried to follow this procedure http://docs.nethserver.org/en/latest/webtop5.html#blank-page-after-login but with no luck.

<details>
 <summary>This is the error stacktrace</summary>

```2018-01-19 16:22:29 [ERROR] c.s.webtop.core.app.ServiceManager - PrivateService: initialize() throws errors [java.lang.ClassCastException: com.sonicle.webtop.core.CoreManager cannot be cast to com.sonicle.webtop.core.admin.CoreAdminManager]
2018-01-19 16:22:29 [ERROR] c.sonicle.webtop.core.servlet.Start - Error
com.sonicle.webtop.core.sdk.WTRuntimeException: Cannot add private service twice
	at com.sonicle.webtop.core.app.WebTopSession.cachePrivateService(WebTopSession.java:590)
	at com.sonicle.webtop.core.app.WebTopSession.internalInitPrivateEnvironment(WebTopSession.java:430)
	at com.sonicle.webtop.core.app.WebTopSession.initPrivateEnvironment(WebTopSession.java:346)
	at com.sonicle.webtop.core.servlet.Start.processRequest(Start.java:89)
	at com.sonicle.webtop.core.app.AbstractServlet.doGet(AbstractServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at com.sonicle.webtop.core.shiro.filter.GZip.doFilterInternal(GZip.java:60)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)


```
</details>

**Comment by gbulfon** [comment]
The admin works fine on the wt5dev, is it the same rpm install?
The stacktrace suggests that there is a double jar of the same service (different versions), as if you have "sonicle-webtop-core-1.2.3.jar" and "sonicle-webtop-core-1.2.4.jar"

**Comment by gsanchietti** [comment]
> The admin works fine on the wt5dev, is it the same rpm install?

I don't know, I don't manage such installation. I've tried on a clean machine with latest built rpm.

> The stacktrace suggests that there is a double jar of the same service (different versions), as if you have "sonicle-webtop-core-1.2.3.jar" and "sonicle-webtop-core-1.2.4.jar"

There is no such file inside the war. 
I can only see something called `webtop-core`:
```
$ unzip -l webtop-webapp-5.war | grep webtop-core
  3982829  01-22-2018 10:37   WEB-INF/lib/webtop-core-5.1.3.jar
  302889  01-22-2018 10:36   WEB-INF/lib/webtop-core-db-5.1.3.jar
  52930  01-22-2018 10:36   WEB-INF/lib/webtop-core-api-5.1.3.jar
```

Well I leave this part of the work to @lucagasparini ;)

Let me know when you think everything is ready to be merge and pushed to testing repositories.

**Comment by lucagasparini** [comment]
I tried on different VMs but I can not replicate the problem that was reported by giacomo.
I can always log in with the WebTop admin user.

**Comment by gbulfon** [comment]
We too cannot replicate it.
What I suggested is to check the deployed WEB-INF/lib for any duplicate library xxx-xxx-1.2.3.jar xxx-xxx-1.2.4.jar : having two different versions of the same service/lib jar may throw the mentioned exception.
If we may have access to a failing machine, we may check directly.

**Comment by gsanchietti** [comment]
Since the bug is not reproducible on your machines, could I merge the PR and move the rpm to testing? @lucagasparini

**Comment by lucagasparini** [comment]
After making further checks, I confirm that you can move the rpm into testing.

**Pull request merged**
